name: go_cab_rider
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^13.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  background_image: "assets/images/splash-background.png"
  image: assets/images/splash-logo.png
  android: true
  ios: true
  android_12:
    background_image: "assets/images/splash_background.png"
    # color: "#F8522E"
    # image: assets/images/trendz-android12-splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/figtree/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/figtree/Figtree-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/figtree/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/figtree/Figtree-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/figtree/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/figtree/Figtree-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/figtree/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/figtree/Figtree-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/figtree/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/figtree/Figtree-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/figtree/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/figtree/Figtree-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/figtree/Figtree-Black.ttf
          weight: 900
        - asset: assets/fonts/figtree/Figtree-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Roobert
      fonts:
        - asset: assets/fonts/Roobert/RoobertLight.ttf
          weight: 300
        - asset: assets/fonts/Roobert/RoobertLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roobert/RoobertRegular.ttf
          weight: 400
        - asset: assets/fonts/Roobert/RoobertRegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roobert/RoobertMedium.ttf
          weight: 500
        - asset: assets/fonts/Roobert/RoobertMediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roobert/RoobertSemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roobert/RoobertSemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roobert/RoobertBold.ttf
          weight: 700
        - asset: assets/fonts/Roobert/RoobertBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roobert/RoobertHeavy.ttf
          weight: 800
        - asset: assets/fonts/Roobert/RoobertHeavyItalic.ttf
          weight: 800
          style: italic
